#!/bin/sh

# Create node binary symlink
command -v node >/dev/null 2>&1 || ln -s /opt/resin.io/node/bin/node /usr/bin/node

# Select the global or local NPM
if command -v npm >/dev/null 2>&1; then
  NPM="npm"
else
  NPM="node /opt/resin.io/node/lib/node_modules/npm/cli.js"
fi

# For debugging purposes
echo "Using node: `node -v`"
echo "Using npm: $NPM"

# Install latest version of the CLI
$NPM install -g resin-cli
